# Generated by Django 4.0.4 on 2023-03-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Beneficiary Name')),
                ('birthdate', models.DateField(verbose_name='Birhtdate')),
                ('gender', models.CharField(max_length=7, verbose_name='Gender')),
                ('relationship', models.CharField(max_length=25, verbose_name='Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default='a1ecc728-8b7a-4bbc-9ef2-32c2b791fc85', max_length=60, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=200, verbose_name='Complete name')),
                ('position', models.CharField(max_length=50)),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('status', models.BooleanField(default=True)),
                ('date_of_hire', models.DateField(verbose_name='Date of Hire')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Photo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.beneficiary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
