# Generated by Django 4.0.4 on 2023-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='ba1b89f7-efe9-469f-a34b-152e19a2109a', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
