# Generated by Django 4.0.4 on 2023-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='39c4025c-cfe1-408f-a8c8-e1bbe01fea7b', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
