# Generated by Django 4.0.4 on 2023-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_user_alter_employee_id_adminstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='eb7cf35a-59dc-411d-b3fa-b38911a48d3b', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
