# Generated by Django 4.0.4 on 2023-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='3e123f7e-728b-472c-8fd1-4dd82ae027aa', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
