# Generated by Django 4.0.4 on 2023-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_id_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='51e9ba5e-f023-4e5c-b418-48bbff6bfce3', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
