# Generated by Django 4.0.4 on 2023-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='a5559542-9cbf-49bb-904b-a56e26e14813', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
