# Generated by Django 4.0.4 on 2023-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='403d3bb6-edb4-48b5-966d-9b4a52b8463c', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
