# Generated by Django 4.0.4 on 2023-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='e615d906-6fdb-4714-9673-71803f593251', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
