# Generated by Django 4.0.4 on 2023-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='949a5c10-e7e6-4818-9506-ef2a715ce381', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
