# Generated by Django 4.0.4 on 2023-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employee_email_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='9abdb6e0-40bd-4896-bf73-26a6ab31b784', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
