# Generated by Django 4.0.4 on 2023-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='005e7b35-0007-4d4b-bdc8-d18f4f670bd5', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
