# Generated by Django 4.0.4 on 2023-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c1d81bf1-df28-4d66-a146-b59f4f97020a', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
