# Generated by Django 4.0.4 on 2023-03-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='a9d149c5-1f7b-470d-a965-f685ce87bd6c', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Photo'),
        ),
    ]
