# Generated by Django 4.0.4 on 2023-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_employee_id_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c37c20c4-c4b9-4486-8ed8-52894f0da607', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
