# Generated by Django 4.0.4 on 2023-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c3813c3b-a4ce-48c3-bf39-41f8b66cbac0', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
