# Generated by Django 4.0.4 on 2023-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='fb7aae62-06e9-4f1a-b069-aea33a162e4c', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
