# Generated by Django 4.0.4 on 2023-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='52c2dd18-9d27-4bc8-a738-a8375c490c3c', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
