# Generated by Django 4.0.4 on 2023-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='13b8f9b0-3465-489a-9303-0d4ce357f8ee', max_length=60, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
